spring.application.name=GAV

pring.data.mongodb.database=gestiondeviajes
spring.data.mongodb.uri=mongodb://localhost:27017/gav
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.session.store-type=redis

#CONSUMO DE API DE MAPAS (MAPBOX)
mapbox.api.token=${MAPBOX_API_TOKEN:sk.eyJ1IjoiZW1tYW51ZWxtb3JpbGxvcCIsImEiOiJjbWg4ZXN1bW4xM2xmMm1vbWNlbjNxdzF2In0.l-1kOAdiC5lzabyx2p4q7g}
mapbox.geocoding.url=https://api.mapbox.com/geocoding/v5/mapbox.places
mapbox.directions.url=https://api.mapbox.com/directions/v5/mapbox/driving
