spring.application.name=GAV

pring.data.mongodb.database=gestiondeviajes
spring.data.mongodb.uri=mongodb://localhost:27017/gav
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.session.store-type=redis