spring.application.name=GAV
#CONEXION CPN MONGODB
spring.data.mongodb.database=gav
spring.data.mongodb.uri=mongodb://localhost:27017/gav

#CONEXION CON REDIS
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=
spring.redis.timeout=5000
spring.redis.lettuce.pool.enabled=true
spring.redis.lettuce.pool.max-active=8
spring.session.store-type=redis
spring.session.redis.flush-mode=on_save
spring.session.redis.namespace=spring:session
spring.session.redis.serializer-type=json

#CONSUMO DE API DE MAPAS (MAPBOX)
mapbox.api.token=${MAPBOX_API_TOKEN:sk.eyJ1IjoiZW1tYW51ZWxtb3JpbGxvcCIsImEiOiJjbWg4ZXN1bW4xM2xmMm1vbWNlbjNxdzF2In0.l-1kOAdiC5lzabyx2p4q7g}
mapbox.geocoding.url=https://api.mapbox.com/geocoding/v5/mapbox.places
mapbox.directions.url=https://api.mapbox.com/directions/v5/mapbox/driving
